### ISSUE TITLE
SyntaxError: Unexpected token '.' for node 13.7

### ISSUE THREAD

**Issue by TomlDev** [RSeidelsohn/license-checker-rseidelsohn#18]
Heyho,
I tried to follow your minimal example and got the following error:
```
tom@nb055:~$ npm install -g license-checker-rseidelsohn
/home/tom/.nvm/versions/node/v13.7.0/bin/license-checker-rseidelsohn -> /home/tom/.nvm/versions/node/v13.7.0/lib/node_modules/license-checker-rseidelsohn/bin/license-checker-rseidelsohn
+ license-checker-rseidelsohn@2.1.1
added 56 packages from 92 contributors in 4.065s
tom@nb055:~$ mkdir foo
tom@nb055:~$ cd foo
tom@nb055:~/foo$ npm install yui-lint
npm WARN saveError ENOENT: no such file or directory, open '/home/tom/foo/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/tom/foo/package.json'
npm WARN foo No description
npm WARN foo No repository field.
npm WARN foo No README data
npm WARN foo No license field.

+ yui-lint@0.2.0
added 1 package and audited 1 package in 0.69s
found 0 vulnerabilities

tom@nb055:~/foo$ license-checker-rseidelsohn
/home/tom/.nvm/versions/node/v13.7.0/lib/node_modules/license-checker-rseidelsohn/lib/index.js:60
        return options?.customFormat?.[property] !== false;
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/tom/.nvm/versions/node/v13.7.0/lib/node_modules/license-checker-rseidelsohn/bin/license-checker-rseidelsohn:9:24)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
```

Versions:
```
tom@nb055:~/foo$ npm version
{
  npm: '6.13.6',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '36.0',
  icu: '65.1',
  llhttp: '2.0.1',
  modules: '79',
  napi: '5',
  nghttp2: '1.40.0',
  node: '13.7.0',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.1',
  v8: '7.9.317.25-node.28',
  zlib: '1.2.11'
}
```

Anything I am doing wrong here? 😄

**Comment by daniel-schulz** [comment]
J4I the status of the build is also `Failing` with a slightly similar error `SyntaxError: Unexpected token '.'` (see the project's [Travis CI](https://www.travis-ci.org/github/rseidelsohn/license-checker-rseidelsohn)). Therefore I guess you're doing everything right and this is a bug.

**Comment by real34** [comment]
Indeed, it seems that https://github.com/RSeidelsohn/license-checker-rseidelsohn/commit/0ed8a22823dd23382aec70a7e0d3e3bb39962315#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1R60 introduced optional chainings `?.` that are only supported since node 14.0.0.

This project may thus have to be marked as 14+ compatible, revert changes to a backwards compatible syntax or transpiled…

**Comment by RSeidelsohn** [comment]
Hi @real34 and @daniel-schulz,

sorry for my late response! I messed things up here and ended up with a slightly messed up versioning. Somehow the version 1.2.2 got lost and now only the latest maintenance release 1.2.3 is uploaded. Version 1.2.2 hangs around here locally as a separate strain and I currently don't know how to bring it back and it's late in the evening (for me at least). I tried your example from above under Ubuntu 21.04 and had no issues whatsoever. So you might want to give v1.2.3 a try?! Be sure to use a separate directory for this. I really apologize for the mess I might have created, but I hope to sort this out soon.
In any case I really want to solve your issues! It would be cool if you could help me and give this version a shot and tell me whether it's now working for you or not.

Btw. I locally use Yarn, but I tried your issue using npm.

Cheers, Roman.

**Comment by daniel-schulz** [comment]
Hi @RSeidelsohn, thank you for your nightly afford and reply.

Regarding version `1.2.3` I could not install it because there is no version tag for this. The latest tag on the 1.x version I've found is `1.2.2`. As @real34 mentioned version **`1.2.2` is working fine on `node v12`**.
When using `nodejs` in `v14` or `v16` also the latest version `2.1.3` is working fine.

Maybe it would be useful to mention in the `ReadMe.md` that `v2.x` works only on `nodejs v14 or higher`  but you can use version `v1.2.2`  if you need to stick with `nodejs v12`.

Cheers, Daniel.
